# These substitutions allow the end user to override certain values
substitutions:
  name: amysen
  friendly_name: "Smart Plug"

esphome:
  name: "${name}"
  # Friendly names are used where appropriate in Home Assistant
  friendly_name: "${friendly_name}"
  # Automatically add the mac address to the name
  # so you can use a single firmware for all devices
  name_add_mac_suffix: true

  # This will allow for (future) project identification,
  # configuration and updates.
  project:
    name: amysenplug.template
    version: "3.0"
  platform: ESP8266
  board: esp01_1m

# To be able to get logs from the device via serial and api.
logger:

# API is a requirement of the dashboard import.
api:

# OTA is required for Over-the-Air updating
ota:
  platform: esphome

# This should point to the public location of this yaml file.
dashboard_import:
  package_import_url: github://stevenjev/amysen/blob/cf6327525ed5a468ad3f0d26e03e061cb567189d/amysenplug-esphome-config.yaml
  import_full_config: false # or true

wifi:
  # Set up a wifi access point
  ap:
  manual_ip:
    static_ip: 192.168.20.243
    gateway: 192.168.1.1
    subnet: 255.255.255.0

# In combination with the `ap` this allows the user
# to provision wifi credentials to the device.
captive_portal:
